### PR TITLE
Mem maze env

### PR DESCRIPTION
**Pull request by zdx3578**
https://github.com/jurgisp/memory-maze. env. add

### CODE REVIEW

**Comment by NM512** [comment]
Hi,

Thanks for making pull request.
Let me tell you points I noticed so far since I'm not in situation to be able to run your code.

1. [memory-maze](https://github.com/jurgisp/memory-maze) seems the environment with discrete action.
So following items should be added for the option for memory-maze in the config file.
- actor_dist: 'onehot'
- imag_gradient: 'reinforce'

    And this change solves the error you encountered [here](https://github.com/NM512/dreamerv3-torch/blob/152415f32e640ce8ab99d7ea4f8dba03a7fcaadf/envs/wrappers.py#L192-L193) which compelled you to make OneHotAction2. Please erase OneHotAction2.

2. It is preferred to name the config option as it is easy to understand.
- mazegym -> memorymaze or memory_maze
- task == '9' -> task == '9x9' or task == 'size9'

3. It looks that unnecessary libraries import exist like threading or traceback maybe used for debug.

4. I think 'is_terminal' should be made True only when episode is terminated in the middle.
So, following change is preferred.
- obs['is_terminal'] = info.get('is_terminal', done) -> obs['is_terminal'] = info.get('is_terminal', False)

By the way, did you encounter the error before you changed np.bool to np.bool_?

**Comment by zdx3578** [comment]
ref: https://github.com/numpy/numpy/issues/22021,when use np.bool will many waring.

**Comment by NM512** [comment]
I confirmed that same warning occur when executing memory-maze.
I'll resolve that soon.

**Comment by NM512** [comment]
I confirmed that same warning occur when executing memory-maze.
I'll resolve that soon.

Thanks for your contribution. :)

**Pull request merged**
